language: scala
jdk: openjdk7
sudo: false
scala:
  - 2.10.6
  - 2.11.7
#cache:
#  directories:
#  - "$HOME/.m2"
#  - "$HOME/.ivy2/cache"
#  - "$HOME/.sbt/boot/"
before_script:
- git config --global user.name "Travis CI"
- git config --global user.email "riomus@gmail.com"
script:
- sbt clean sparkling-graph-loaders/test:test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
#- bash <(curl -s https://codecov.io/bash)
#- sbt ghpages-push-site
#- sbt publish

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a7f41d0591e65e9122c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

env:
  global:
  - SBT_GHPAGES_COMMIT_MESSAGE='[ci skip] page update'
  - secure: F2p0cLEv6KmncFCve8M+RMO2oBafDf5HC8crRlVa/8PWOUyxofSkYY0YH8WpIGVlUmpw+s6MWizUotfWep6mRrhqiHx5aGxD35jG46IV0UjKoT8IrkJ/KnheJQVJ0S+R9rRDOmSZflGCg2hMWMrtzg8QYjYihoMaN1l6zJh2s8dzyWtzaHv7eKyZhiu/Qd1xq3za8FD8tli+d46eYYyzqKX3W0vaRXmZ+hkax3m0ks7IaF665iHX/4nUw3TeDtzOhmUKtTrQ2LTyiRROPUYokNpriTXJTSfs+0qFkDvPqXyxWPLtf/WZfv1B8M5kvfHXRA6K17+RxhP89mIIUE+xpb+spszZaUDCkpWo605fEwCl1I9fNzl2eiPjVQhkjorr0BMU5RtMQwPHwuzJdj7F+ZfmpuinHugQNen6ciNHO9LOrNi8CNSnPVHlla/nQ5Hnsmz8xHD+o42mmzleL1IFrtGYnI01twxt8JkPHBI84850ulDdb5VJmcC5zyhXc82Jd9xqQpXjf2rqDCKzmeDc1TI7XNmyJvv3OzeLnU9bMJXq+6CxRFz49fwhuna1h9B9oZ7SCVUCWav6zbowtNL91rR3/kcyYJvAja4UsRdzUN9NAn+yTSLsCdQAFSezLEtSiv8eBomEnZzxThzcEXrneMpSRRS8BaF9f9IbFLND9fA=
  - secure: FKuvVFlZPHLE79Y0gEsoh+XXW2C9S+mtuJTCRuysi4jbbzPx7NpRK8epD0IcF7Kb2ySD1dJM5jXzzsIaTPSx+JnSL6nLOXE8fPpt9B+5AxTnz2C2wEPKtIxjUWp/kK/85MfuuNrg/4+KmZDS44BUAjT81LUlOPGH1CU6MBLnBUTsOFSAn1bCm5gDUhXrzX5fwXl+SvNx9s1HnWf4LC7YGKaIVS/VCwoIw9gfDMysayfPx/MOepYO5UILcUNLbd8ZQZb1rDaY9vGkDD+qUSbqtT2M5iGEcRpnPWdyr2iN5y6gf2y9gl56Sou+PmxWBJfQooYVxeHtS5NR8Tni0Uh7/IziCgpEwMqzESFLM/7hv8achTaKp9tcd2YtzfKkA/swSVrlCPypNWrjZ5jGB/rw0Dbv0HFJsvDYxL5J0G4kl3ctlQSZcma7WfqHGJJPjtBIDn7gqCcKHp5ojxSOjzLq5iCKNyqlAAT3RXoG185tj5rIDdsTNdSJ5O/PUhzNMgEfReQBzIvpumJRnUBN7h7QqPdw78ZMwIinHJnP9V7S/8gnCFisJ+hRBuPSJK22pxO9FFtL7qZsoFIkVpfGCiZ323cSST2IAhz84d+T6RpwbGKdEUVWBzIEPF77WaTmHxkkLzEr8qvpuwRMYUkqy34v15aGmYeogIC23oCVw/ecX90=
  - secure: k0Ms8O6kYP5LhWozlrEZ/YdgqOKeE20/eMvCHBloWgLi+hLG+LWvZVG7v2BWcHTRVORwhCf0HDwm111M1pv9YCFhtKFrPILmabv68MxwH3AaBy/ZQlBlAyoazU2AdOcH7zpoovccd/wPakcVJ7CemRNJmHdipGelt5juC9MeZr6fGt7f3dCO49u37Gs/I6UpOaSP8JXVhsPhrYlhvwteBFL77uf34EGWSN1BgwahyUw1iI+g4r2gRokDen4hPetgKVx299Ds891vpXQWFC3p4Hm6Mo1iLTcu2CHXVf0hIfG70FUaSazyZ3pMGhMo87HSIoCL8Odhnb+nClGRYv8l6ICSXX8qor1E/fXCM3Zg55Is28aRJ6qtTa0MD50J+Q1o4xkEXXQmX8HWWulwue7DOwaYeERgqilzqAK8f1kn9pLkao0cK42eS1ge9hjycG4WYSMjlYTEtQ92o0/dLdiayEzCC0ZSt4+A/uxGG2MyfePLwTbcyGqbxzc+L/uiToVS14MeCIUSGhZA7aq9mBItVUyiBdeaXYs+Xx1r3hAm/oOLAf+izjUhnyNmObv7VXcebXLo9x9deNT+CFotxO/4XddGY5ccjY0UnoHkM82j/KCtI3LyKd86z8RjwODQ9pwc/Syf/M1DYRIEKHN/DkbvA3ctsiG3SfCtIE6ioa2cQW8=
  - secure: V+TJlEGki5cmw5ZTBKmXjtXShEG7HcnF1vq15nRtKv9o7bLK719/+0n7kLkHzicovUWKiinIadQ5160XukgPcKaWhz3CAIi1ZDP8gynMiiy8p/GR+cUcIFMSPr4FKGVs90Vx8ba9nsPNXBRbM00esAe4Kk+CtPL1OzLf1MUKv/Wl8Wt058udRLmqwt4vWDIIoVaAuAfwdk+b1eab+rKxaw76MmwKCe79uaPdvRPWNgD+jtrzMmn67H56b51WX+XAYGCgmpdZZWxoMZeai8bcmYoX06zrZ3VvvBdici1LMuV/cwmPxAZ6B9BvR6yMumbksEdUPe1xlqLGfJkf5l5QLR+Qb+jk3UTQw2znzN5xzEw+ABtWWUOvN/kPIc5rdx4AYACu4Z5oUHfDmh0lLzcSz7tyis7JIsqO0YWQKe3fyHJftwjyBeNCaK8oJbli4t3AUxJlM4WOFeYCtKQkCzHSuCBDIBFilIijYEmWYxuXTgAZGeOw3FbNTMArjLFxwO5s3JDpR1pldEyn+toHYgCz3fIN/DJOqQ8hbYlW1RDfxI87WZ50aY/Cfiko6llNCXfforNpCQHs+O4+NDDxOiEQ+sDvQ/oaKJbjDdF4boOcfLLR2C0UaQ/gs4L1u6zVb8pU8YzC98MZOq7+8uwk2EUo7kcYWHg+kAOjdDiR4qTk0zs=
  - secure: CuxDj9QaRytfJ9g8JukBah9HyZT8oyRGq8bFGz3B3R2+W0ojZ7eTA0lzSCcwIAfrx6FcCRIc6Zu+ZIBcOVW5qwrVu2XTXo2bEvnnPqKIZjjiYP8JEPSD7+0zXlgzJd79bBF/Bb71SvYeZ8N68Idl8MrCBj1YUR95bizYiaCclnL+XrIV4h8PKZ3Cuh5tmi9XUIPLTje0guHi6GF+cTEGH7BQ5vXqlk1AIHH0SCJHUZ6p6zbM/+500km+BfLdd3p3l7NYDHngKisOlIeX1MkbxyGjmXHEwKP1xAOqcUZmsQDEULIEZvvVo3yVEVAWy8dWhQRVcN3v6jLe7Z8zt9/tDVsC15Hncmfy9BbuqM8HmgXi8l5qjcipSrltrgyKK/IlmNKmIlLtNNlvU0QV0cvYY6JnBmv3JX6hjlCRsnNUKq36lbqPLH/n+jSJChPE2QnceqZvKjrj66lpwx3MYRu3cbvpfP1NOXb5vJ4tf2h5SRQ0gTDBdejsnNwjpmIsGAx2WW+TU5MEveVHFUtcN22YVL20yJ2+C0QSVjY/9vdQbNIbHDZ58IGZ0fy8zgjpGKhll+8xnI4HKmBDbOAXbpuUWlDc+2iRl6pJGqelqLy4bk57xf7WUj18e56XOMP8gY+tqJJC2X6lM2kMoq82pGi4gX/HBNlXHKXyszu7DF094s0=
